# Generated by Django 3.2 on 2023-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('jumlah', models.CharField(max_length=255)),
                ('harga', models.CharField(max_length=255)),
            ],
        ),
    ]
